---
# Docker Compose for quick testing of ansible-mysql role
# Usage: docker compose up -d && docker compose exec mysql-test bash

services:
  mysql-test:
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    container_name: ansible-mysql-test
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .:/penwern.mysql:ro
      - ./test-inventory:/inventory:ro
    tmpfs:
      - /run
      - /tmp
    command: /sbin/init
    environment:
      - container=docker
    networks:
      - mysql-test-net
    ports:
      - "3306:3306"

networks:
  mysql-test-net:
    driver: bridge
