---
# Sample inventory for testing ansible-mysql role
all:
  hosts:
    localhost:
      ansible_connection: local
      mysql_root_password: "test_password_123!"
      mysql_bind_address: "0.0.0.0"
      mysql_users:
        - name: test_user
          host: localhost
          password: test_user_password
          priv: test_db.*:ALL
          state: present
      mysql_databases:
        - name: test_db
          collation: utf8mb4_unicode_ci
          encoding: utf8mb4
          state: present
