---
# Sample playbook for testing ansible-mysql role
# Usage: ansible-playbook -i test-inventory/hosts.yml test-inventory/test-playbook.yml

- name: Test MySQL Role
  hosts: localhost
  become: true
  gather_facts: true

  roles:
    - role: penwern.mysql

  post_tasks:
    - name: Verify MySQL is running
      ansible.builtin.service:
        name: mysql
        state: started
      register: mysql_status

    - name: Display MySQL status
      ansible.builtin.debug:
        msg: "MySQL service is {{ mysql_status.state }}"

    - name: Test database connection
      community.mysql.mysql_query:
        login_user: test_user
        login_password: test_user_password
        login_db: test_db
        query: "SELECT 'Connection successful' as status"
      register: connection_test

    - name: Display connection test result
      ansible.builtin.debug:
        msg: "{{ connection_test.query_result[0][0].status }}"
