# SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-mysql

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  tags: mysql

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto
  tags: mysql

- name: MySQL pre-installation tasks
  ansible.builtin.include_tasks: pre_install.yml
  tags:
    - mysql
    - mysql_install

- name: MySQL installation
  ansible.builtin.include_tasks: install.yml
  tags:
    - mysql
    - mysql_install

- name: MySQL post-installation configuration
  ansible.builtin.include_tasks: post_install.yml
  tags:
    - mysql
    - mysql_config

- name: Check if MySQL secure installation marker exists
  ansible.builtin.stat:
    path: "{{ mysql_secure_installation_marker }}"
  register: installation_marker_stat
  tags:
    - mysql
    - mysql_secure

- name: MySQL secure installation
  ansible.builtin.include_tasks: mysql_secure_installation.yml
  when: not installation_marker_stat.stat.exists
  tags:
    - mysql
    - mysql_secure

- name: Create marker file for MySQL secure installation
  ansible.builtin.file:
    path: "{{ mysql_secure_installation_marker }}"
    state: touch
    mode: "0644"
  when: not installation_marker_stat.stat.exists
  tags:
    - mysql
    - mysql_secure

- name: Configure MySQL
  ansible.builtin.include_tasks: configure.yml
  tags:
    - mysql
    - mysql_config

- name: MySQL user management
  ansible.builtin.include_tasks: users.yml
  when: mysql_users is defined and mysql_users | length > 0
  tags:
    - mysql
    - mysql_users

- name: MySQL database management
  ansible.builtin.include_tasks: databases.yml
  when: mysql_databases is defined and mysql_databases | length > 0
  tags:
    - mysql
    - mysql_databases

- name: Ensure MySQL is started and enabled
  ansible.builtin.systemd:
    name: "{{ mysql_service_name }}"
    state: started
    enabled: true
  tags: mysql
