---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache (Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

    - name: Install Python3 and pip
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install PyMySQL Python package
      ansible.builtin.pip:
        name: pymysql
        state: present

  roles:
    - role: penwern.mysql

  post_tasks:
    - name: Wait for MySQL to be ready
      ansible.builtin.wait_for:
        port: 3306
        host: "{{ mysql_bind_address | default('127.0.0.1') }}"
        delay: 5
        timeout: 300

    - name: Verify MySQL service is running
      ansible.builtin.service:
        name: mysql
        state: started
      check_mode: true
      register: mysql_service_status

    - name: Display MySQL service status
      ansible.builtin.debug:
        var: mysql_service_status
