---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: penwern.mysql

  post_tasks:
    - name: Wait for MySQL to be ready
      ansible.builtin.wait_for:
        port: 3306
        host: "{{ mysql_bind_address | default('127.0.0.1') }}"
        delay: 5
        timeout: 300

    - name: Verify MySQL service is running
      ansible.builtin.service:
        name: mysql
        state: started
      check_mode: true
      register: mysql_service_status

    - name: Display MySQL service status
      ansible.builtin.debug:
        var: mysql_service_status
      no_log: true
