---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache (Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
        lock_timeout: 120
      when: ansible_os_family == "Debian"

    - name: Install required system packages
      ansible.builtin.package:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Python3 and pip
      ansible.builtin.package:
        name:
          - python3
          - python3-pip
          - python3-setuptools
        state: present

    - name: Install Python MySQL library
      ansible.builtin.pip:
        name:
          - pymysql
          - cryptography
        state: present

    - name: Ensure systemd is available
      ansible.builtin.command: systemctl --version
      register: systemd_check
      changed_when: false

    - name: Display systemd version
      ansible.builtin.debug:
        msg: "Systemd version: {{ systemd_check.stdout_lines[0] }}"
