name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 6 * * 0'

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync
          pip install --upgrade pip
          pip install yamllint ansible-core==2.17.7 ansible-lint molecule molecule-plugins[docker] pytest pytest-ansible pymysql cryptography

      - name: Lint
        run: |
          yamllint .
          ansible-lint

      - name: Security scan
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown

      - name: Install ansible collections
        run: |
          ansible-galaxy collection install community.general

      - name: Molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ubuntu2404
