name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: '0 6 * * 0'

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PIP_ROOT_USER_ACTION: ignore

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Cache Ansible collections
        uses: actions/cache@v4
        with:
          path: ~/.ansible/collections
          key: ${{ runner.os }}-ansible-collections-${{ hashFiles('requirements.yml') }}
          restore-keys: |
            ${{ runner.os }}-ansible-collections-

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y  rsync

      - name: Install Python dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Activate virtual environment
        run: |
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Lint
        run: |
          yamllint .
          ansible-lint

      - name: Security scan
        uses: trufflesecurity/trufflehog@v3.89.2
        with:
          extra_args: --results=verified,unknown

      - name: Install ansible collections
        run: |
          ansible-galaxy collection install -r requirements.yml

      - name: Molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
